import { Router, Request, Response, NextFunction } from "express";
import { CourseSectionRepository } from "../../repositories/courseSectionRepository";
import { getUploadStatistics, uploadData } from "../../controllers/v1/uploadControllerV1";
import multer from "multer";
import { StatusCodes } from "http-status-codes";

export function uploadRoutesV1(repo: CourseSectionRepository): Router {
	const r = Router({ mergeParams: true });

	const upload = multer({ storage: multer.memoryStorage() });
	const multerUpload = upload.single("archive");

	// below generated by Gemini
	const safeUploadMiddleware = (req: Request, res: Response, next: NextFunction): void => {
		void multerUpload(req, res, (err) => {
			if (err) {
				console.log(err);
				const validationErrors: Record<string, string> = {};

				if (req.body.kind === undefined) {
					validationErrors.kind = "required but missing";
				} else if (req.body.kind !== "course_offerings") {
					validationErrors.kind = "expected to be course_offerings";
				}

				if (!req.file) {
					validationErrors.archive = "required but missing";
				} else if (req.file.size === 0) {
					validationErrors.archive = "expected non-empty file";
				}

				return res.status(StatusCodes.UNPROCESSABLE_ENTITY).json({
					error: "Validation failed",
					fields: validationErrors,
				});
			}

			next();
		});
	};
	// above generated by Gemini

	r.post("/", safeUploadMiddleware, async (req, res) => uploadData(req, res, repo));
	r.get("/:id", async (req, res) => getUploadStatistics(req, res, repo));

	return r;
}
