import { useState } from "react";
import {
	Paper,
	CircularProgress,
	Alert,
	Button,
	Typography,
	List,
	ListItem,
	Collapse,
	ListItemButton,
	Stack,
	Box,
	Divider,
} from "@mui/material";
import ExpandLess from "@mui/icons-material/ExpandLess";
import ExpandMore from "@mui/icons-material/ExpandMore";
import CloudUploadIcon from "@mui/icons-material/CloudUpload";
import api from "../api/axios";
import { AxiosError, type AxiosResponse } from "axios";

export interface JobMsg {
	id: string;
	status: string;
	kind: string;
	message: string;
	stats: {
		files_total: number;
		files_processed: number;
		files_skipped: number;
		courses_seen: number;
		courses_added: number;
		courses_modified: number;
		sections_seen: number;
		sections_added: number;
		sections_modified: number;
	};
}

export default function DataUpload({ setNewData }: { setNewData: React.Dispatch<React.SetStateAction<boolean>> }) {
	const [open, setOpen] = useState<boolean>(true);
	const [statusMsg, setStatus] = useState<JobMsg | null>(null);
	const [loading, setLoading] = useState<boolean>(false);
	const [selectedFile, setFile] = useState<File | null>(null);
	const [error, setError] = useState<string | null>(null);

	async function pollForCompletion(res: AxiosResponse<JobMsg>) {
		try {
			const response = await api.get(`/v1/datasets/${res.data.id}`);
			if (response.data.status === "completed") {
				setLoading(false);
				setStatus(response.data);
				setNewData(true);
				return;
			} else if (response.data.status === "failed") {
				setLoading(false);
				setError(response.data.message);
				return;
			} else {
				setTimeout(pollForCompletion, 1000, response);
			}
			// below generated by Gemini
		} catch (err) {
			if (err instanceof AxiosError) {
				let errorMessage;
				if (err.response?.data?.error && err.response?.data?.message) {
					errorMessage = `${err.response.data.error}: ${err.response.data.message}`;
				} else {
					errorMessage = err.response?.data?.error || err.message || "Failed to poll dataset status";
				}
				setError(errorMessage);
			} else if (err instanceof Error) {
				setError(err.message);
			}
			setLoading(false);
		}
		// above generated by Gemini
	}

	const uploadFile = async () => {
		if (selectedFile) {
			const formData = new FormData();
			formData.append("kind", "course_offerings");
			formData.append("archive", selectedFile);

			try {
				setLoading(true);
				setError(null);
				setStatus(null);

				const response = await api.post("/v1/datasets", formData, {
					headers: { "Content-Type": "multipart/form-data" },
				});

				pollForCompletion(response);
				// below generated by Gemini
			} catch (err) {
				if (err instanceof AxiosError) {
					let errorMessage;
					if (err.response?.data?.error && err.response?.data?.message) {
						errorMessage = `${err.response.data.error}: ${err.response.data.message}`;
					} else {
						errorMessage = err.response?.data?.error || err.message || "Failed to upload";
					}
					setError(errorMessage);
				} else if (err instanceof Error) {
					setError(err.message);
				}
				setLoading(false);
			}
			// above is AI generated
		}
	};

	const handleClick = () => {
		setOpen(!open);
	};

	return (
		<Paper sx={{ p: 3, mb: 3 }}>
			<Typography variant="h6" gutterBottom>
				Dataset Management
			</Typography>

			{error && (
				<Alert severity="error" sx={{ mb: 2 }}>
					{error}
				</Alert>
			)}

			{/* --- Upload Controls --- */}
			<Stack direction={{ xs: "column", sm: "row" }} spacing={2} alignItems="center" sx={{ my: 2 }}>
				<Button component="label" variant="outlined" startIcon={<CloudUploadIcon />} disabled={loading}>
					Select Zip File
					<input
						type="file"
						accept=".zip,application/zip"
						// below generated by Gemini
						onChange={(e) => {
							if (e.target.files && e.target.files[0]) {
								setFile(e.target.files[0]);
								setError(null); // Clear previous errors immediately
								setStatus(null);
							}
						}}
						style={{ display: "none" }}
						// above generated by Gemini
					/>
				</Button>

				{selectedFile ? (
					<Typography variant="body2" color="text.secondary" sx={{ flexGrow: 1 }}>
						Selected: <strong>{selectedFile.name}</strong> ({(selectedFile.size / 1024 / 1024).toFixed(2)} MB)
					</Typography>
				) : (
					<Typography variant="body2" color="text.secondary" sx={{ flexGrow: 1 }}>
						No file selected.
					</Typography>
				)}

				<Button variant="contained" onClick={uploadFile} disabled={!selectedFile || loading}>
					Upload Dataset
				</Button>
			</Stack>

			{/* --- Loading State --- */}
			{loading && (
				<Box
					sx={{ display: "flex", alignItems: "center", gap: 2, mt: 3, p: 2, bgcolor: "action.hover", borderRadius: 1 }}
				>
					<CircularProgress size={24} />
					<Typography color="text.secondary">Processing dataset on server...</Typography>
				</Box>
			)}

			{/* --- Results State --- */}
			{statusMsg && statusMsg.status === "completed" && (
				<Box sx={{ mt: 3 }}>
					<Alert severity="success" sx={{ mb: 2 }}>
						Dataset successfully processed!
					</Alert>

					<Divider sx={{ my: 2 }} />

					<List disablePadding>
						<ListItemButton onClick={handleClick} sx={{ bgcolor: "action.hover", borderRadius: 1 }}>
							<Typography variant="subtitle2" sx={{ flexGrow: 1 }}>
								Detailed Processing Statistics
							</Typography>
							{open ? <ExpandLess /> : <ExpandMore />}
						</ListItemButton>
						<Collapse in={open}>
							<Stack direction={{ xs: "column", md: "row" }} spacing={4} sx={{ p: 2 }}>
								<List dense sx={{ flex: 1 }}>
									<ListItem>
										<strong>Total files:</strong> &nbsp; {statusMsg.stats.files_total}
									</ListItem>
									<ListItem>
										<strong>Files processed:</strong> &nbsp; {statusMsg.stats.files_processed}
									</ListItem>
									<ListItem>
										<strong>Files skipped:</strong> &nbsp; {statusMsg.stats.files_skipped}
									</ListItem>
								</List>
								<List dense sx={{ flex: 1 }}>
									<ListItem>
										<strong>Courses seen:</strong> &nbsp; {statusMsg.stats.courses_seen}
									</ListItem>
									<ListItem>
										<strong>Courses added:</strong> &nbsp; {statusMsg.stats.courses_added}
									</ListItem>
									<ListItem>
										<strong>Courses modified:</strong> &nbsp; {statusMsg.stats.courses_modified}
									</ListItem>
								</List>
								<List dense sx={{ flex: 1 }}>
									<ListItem>
										<strong>Sections seen:</strong> &nbsp; {statusMsg.stats.sections_seen}
									</ListItem>
									<ListItem>
										<strong>Sections added:</strong> &nbsp; {statusMsg.stats.sections_added}
									</ListItem>
									<ListItem>
										<strong>Sections modified:</strong> &nbsp; {statusMsg.stats.sections_modified}
									</ListItem>
								</List>
							</Stack>
						</Collapse>
					</List>
				</Box>
			)}
		</Paper>
	);
}
// debugged last grid section (one that displays statusMsg) with Gemini
// used https://mui.com/material-ui/react-list/ for setting up collapsing function for upload stats
