import { useState, useEffect, useCallback, useMemo } from "react";
import {
	Table,
	TableBody,
	TableCell,
	TableContainer,
	TableHead,
	TableRow,
	Paper,
	CircularProgress,
	Alert,
	TextField,
	Button,
	Stack,
	TableSortLabel,
	Typography,
	InputAdornment,
	Divider,
} from "@mui/material";

// --- below UI styling generated by Gemini (Icons) ---
import FilterAltIcon from "@mui/icons-material/FilterAlt";
import SearchIcon from "@mui/icons-material/Search";
import BusinessIcon from "@mui/icons-material/Business";
import PersonIcon from "@mui/icons-material/Person";
import CalendarTodayIcon from "@mui/icons-material/CalendarToday";
import InboxIcon from "@mui/icons-material/Inbox";
// --- above UI styling generated by Gemini (Icons) ---

import api from "../api/axios";
import { AxiosError } from "axios";

export interface SectionData {
	dept: string;
	code: string;
	title: string;
	year: number;
	instructor: string;
	avg: number;
}

// below generated by Gemini

export default function DataExplorer({
	newData,
	setNewData,
}: {
	newData: boolean;
	setNewData: React.Dispatch<React.SetStateAction<boolean>>;
}) {
	const [data, setData] = useState<SectionData[]>([]);
	const [loading, setLoading] = useState<boolean>(true);
	const [error, setError] = useState<string | null>(null);

	// --- Filter State ---
	const [departments, setDepartments] = useState<string>("");
	const [yearStart, setYearStart] = useState<string>("");
	const [yearEnd, setYearEnd] = useState<string>("");
	const [instructor, setInstructor] = useState<string>("");

	// --- below UI styling generated by Gemini (Sort State) ---
	// Track active column for the UI sort arrows
	const [activeSort, setActiveSort] = useState<string>("dept");
	// --- above UI styling generated by Gemini (Sort State) ---

	// --- 1. Pure Fetch Function ---
	const performFetch = useCallback(async (payload: unknown) => {
		setLoading(true);
		setError(null);
		try {
			const response = await api.post("/v1/search", payload);
			setData(response.data);
		} catch (err: unknown) {
			if (err instanceof AxiosError) {
				let errorMessage;
				if (err.response?.data?.error && err.response?.data?.message) {
					errorMessage = `${err.response.data.error}: ${err.response.data.message}`;
				} else {
					errorMessage = err.response?.data?.error || err.message || "Failed to fetch data";
				}
				setError(errorMessage);
			} else if (err instanceof Error) {
				setError(err.message);
			}
		} finally {
			setLoading(false);
		}
	}, []);

	// --- 2. Initial Load Effect ---
	useEffect(() => {
		performFetch({
			kind: "course_offerings",
			query: {
				WHERE: {},
				OPTIONS: {
					COLUMNS: ["dept", "code", "title", "year", "instructor", "avg"],
					ORDER: "dept",
				},
			},
		});
	}, [performFetch]);

	// --- 3. Fetch if new data is loaded ---
	useEffect(() => {
		if (newData) {
			performFetch({
				kind: "course_offerings",
				query: {
					WHERE: {},
					OPTIONS: {
						COLUMNS: ["dept", "code", "title", "year", "instructor", "avg"],
						ORDER: "dept",
					},
				},
			});
			setNewData(false); // Reset the newData flag after fetching
		}
	}, [newData]);

	type FilterCondition =
		| { IS: { [key: string]: string } }
		| { GT: { [key: string]: number } }
		| { LT: { [key: string]: number } }
		| { OR: FilterCondition[] }
		| { AND: FilterCondition[] };

	function getFilters(): FilterCondition[] {
		const filters: FilterCondition[] = [];

		if (instructor.trim()) {
			filters.push({ IS: { instructor: `${instructor.trim()}` } });
		}

		if (yearStart) {
			filters.push({ GT: { year: parseInt(yearStart, 10) - 1 } });
		}

		if (yearEnd) {
			filters.push({ LT: { year: parseInt(yearEnd, 10) + 1 } });
		}

		const deptArray = departments
			.split(",")
			.map((d) => d.trim().toLowerCase())
			.filter((d) => d !== "");

		if (deptArray.length === 1) {
			filters.push({ IS: { dept: deptArray[0] } });
		} else if (deptArray.length > 1) {
			const orFilters = deptArray.map((d) => ({ IS: { dept: d } }));
			filters.push({ OR: orFilters });
		}
		return filters;
	}

	// --- 3. Button Click Handler ---
	const handleSearch = () => {
		const filters = getFilters();
		let WHERE = {};
		if (filters.length === 1) {
			WHERE = filters[0];
		} else if (filters.length > 1) {
			WHERE = { AND: filters };
		}

		const payload = {
			kind: "course_offerings",
			query: {
				WHERE,
				OPTIONS: {
					COLUMNS: ["dept", "code", "title", "year", "instructor", "avg"],
					ORDER: activeSort, // Keep current sort when searching
				},
			},
		};

		performFetch(payload);
	};

	const handleSort = (key: string) => () => {
		setActiveSort(key); // --- UI styling generated by Gemini ---

		const filters = getFilters();
		let WHERE = {};
		if (filters.length === 1) {
			WHERE = filters[0];
		} else if (filters.length > 1) {
			WHERE = { AND: filters };
		}
		performFetch({
			kind: "course_offerings",
			query: {
				WHERE,
				OPTIONS: {
					COLUMNS: ["dept", "code", "title", "year", "instructor", "avg"],
					ORDER: key,
				},
			},
		});
	};

	const memoizedTableBody = useMemo(() => {
		if (data.length === 0) {
			return (
				<TableRow>
					{/* --- below UI styling generated by Gemini (Empty State) --- */}
					<TableCell colSpan={6} align="center" sx={{ py: 8 }}>
						<InboxIcon sx={{ fontSize: 48, color: "text.disabled", mb: 2 }} />
						<Typography variant="h6" color="text.secondary">
							No data found
						</Typography>
						<Typography variant="body2" color="text.secondary">
							Try adjusting your filters or uploading a dataset.
						</Typography>
					</TableCell>
					{/* --- above UI styling generated by Gemini (Empty State) --- */}
				</TableRow>
			);
		}

		return data.map((row, index) => (
			// --- below UI styling generated by Gemini (Zebra Striping & Alignment) ---
			<TableRow key={index} hover sx={{ "&:nth-of-type(odd)": { backgroundColor: "rgba(0, 0, 0, 0.02)" } }}>
				<TableCell>{row.dept}</TableCell>
				<TableCell>{row.code}</TableCell>
				<TableCell>{row.title}</TableCell>
				<TableCell align="right">{row.year}</TableCell>
				<TableCell>{row.instructor}</TableCell>
				<TableCell align="right">{row.avg}</TableCell>
			</TableRow>
			// --- above UI styling generated by Gemini (Zebra Striping & Alignment) ---
		));
	}, [data]);

	return (
		<>
			{/* --- below UI styling generated by Gemini (Filter Panel Overhaul) --- */}
			<Paper sx={{ p: 3, mb: 3 }} elevation={2}>
				<Typography variant="h6" sx={{ display: "flex", alignItems: "center", mb: 2, gap: 1, color: "primary.main" }}>
					<FilterAltIcon /> Query Filters
				</Typography>
				<Divider sx={{ mb: 3 }} />

				<Stack spacing={3}>
					{/* Top Row: Text Filters */}
					<Stack direction={{ xs: "column", sm: "row" }} spacing={3}>
						<TextField
							label="Departments (e.g. cpsc, math)"
							variant="outlined"
							size="small"
							value={departments}
							onChange={(e) => setDepartments(e.target.value)}
							fullWidth
							InputProps={{
								startAdornment: (
									<InputAdornment position="start">
										<BusinessIcon fontSize="small" />
									</InputAdornment>
								),
							}}
						/>
						<TextField
							label="Instructor (e.g. holmes)"
							variant="outlined"
							size="small"
							value={instructor}
							onChange={(e) => setInstructor(e.target.value)}
							fullWidth
							InputProps={{
								startAdornment: (
									<InputAdornment position="start">
										<PersonIcon fontSize="small" />
									</InputAdornment>
								),
							}}
						/>
					</Stack>

					{/* Bottom Row: Number Filters & Action */}
					<Stack direction={{ xs: "column", sm: "row" }} spacing={3} alignItems="flex-start">
						<TextField
							label="Year Start"
							type="number"
							variant="outlined"
							size="small"
							value={yearStart}
							onChange={(e) => setYearStart(e.target.value)}
							fullWidth
							InputProps={{
								startAdornment: (
									<InputAdornment position="start">
										<CalendarTodayIcon fontSize="small" />
									</InputAdornment>
								),
							}}
						/>
						<TextField
							label="Year End"
							type="number"
							variant="outlined"
							size="small"
							value={yearEnd}
							onChange={(e) => setYearEnd(e.target.value)}
							fullWidth
							InputProps={{
								startAdornment: (
									<InputAdornment position="start">
										<CalendarTodayIcon fontSize="small" />
									</InputAdornment>
								),
							}}
						/>
						<Button
							variant="contained"
							size="large"
							onClick={handleSearch}
							disabled={loading}
							startIcon={loading ? <CircularProgress size={20} color="inherit" /> : <SearchIcon />}
							sx={{ minWidth: 150, height: 40 }}
							fullWidth
						>
							{loading ? "Searching..." : "Search"}
						</Button>
					</Stack>
				</Stack>
			</Paper>
			{/* --- above UI styling generated by Gemini (Filter Panel Overhaul) --- */}

			{error && (
				<Alert severity="error" sx={{ mb: 2 }}>
					{error}
				</Alert>
			)}

			{/* --- Data Table --- */}
			{!error && (
				<TableContainer component={Paper} sx={{ maxHeight: 600 }} elevation={2}>
					<Table stickyHeader size="small">
						{/* --- below UI styling generated by Gemini (Table Headers & Active Sort) --- */}
						<TableHead>
							<TableRow>
								<TableCell sx={{ fontWeight: "bold", bgcolor: "grey.100" }}>
									<TableSortLabel active={activeSort === "dept"} onClick={handleSort("dept")}>
										Dept
									</TableSortLabel>
								</TableCell>
								<TableCell sx={{ fontWeight: "bold", bgcolor: "grey.100" }}>
									<TableSortLabel active={activeSort === "code"} onClick={handleSort("code")}>
										Code
									</TableSortLabel>
								</TableCell>
								<TableCell sx={{ fontWeight: "bold", bgcolor: "grey.100" }}>
									<TableSortLabel active={activeSort === "title"} onClick={handleSort("title")}>
										Title
									</TableSortLabel>
								</TableCell>
								<TableCell sx={{ fontWeight: "bold", bgcolor: "grey.100" }} align="right">
									<TableSortLabel active={activeSort === "year"} onClick={handleSort("year")}>
										Year
									</TableSortLabel>
								</TableCell>
								<TableCell sx={{ fontWeight: "bold", bgcolor: "grey.100" }}>
									<TableSortLabel active={activeSort === "instructor"} onClick={handleSort("instructor")}>
										Instructor
									</TableSortLabel>
								</TableCell>
								<TableCell sx={{ fontWeight: "bold", bgcolor: "grey.100" }} align="right">
									<TableSortLabel active={activeSort === "avg"} onClick={handleSort("avg")}>
										Avg
									</TableSortLabel>
								</TableCell>
							</TableRow>
						</TableHead>
						{/* --- above UI styling generated by Gemini (Table Headers & Active Sort) --- */}

						<TableBody>
							{/* --- below UI styling generated by Gemini (Inline Loading) --- */}
							{loading && data.length === 0 ? (
								<TableRow>
									<TableCell colSpan={6} align="center" sx={{ py: 10 }}>
										<CircularProgress />
										<Typography color="text.secondary" sx={{ mt: 2 }}>
											Loading dataset...
										</Typography>
									</TableCell>
								</TableRow>
							) : (
								memoizedTableBody
							)}
							{/* --- above UI styling generated by Gemini (Inline Loading) --- */}
						</TableBody>
					</Table>
				</TableContainer>
			)}
		</>
	);
}

// above generated by Gemini
