import { StatusCodes } from "http-status-codes";
import { CourseSectionRepository } from "../repositories/courseSectionRepository";
import type { Request, Response } from "express";
import { sendNotFound, validateQuery } from "./courseControllers";
import { Section } from "../models/section";

function formatItemResponse(req: Request, paginatedResults: Section[]): any {
	return paginatedResults.map((section) => {
		return {
			id: section.id,
			instructor: section.instructor,
			year: section.year,
			avg: section.avg,
			pass: section.pass,
			fail: section.fail,
			audit: section.audit,
			links: {
				self: `${req.originalUrl}`.split("?")[0] + "/" + section.id,
				course: `${req.originalUrl}`.split("/sections")[0],
			},
		};
	});
}
export async function listSections(req: Request, res: Response, repo: CourseSectionRepository): Promise<void> {
	const course = await repo.getCourseByIdAsync(req.params.courseId);
	if (course === undefined) {
		sendNotFound(res, req.params.courseId, "course");
		return;
	}

	// code below based off sample implementation given in C1 assignment info - https://canvas.ubc.ca/courses/176257/assignments/2334739
	// Extract pagination parameters from query string
	// URL: /courses?limit=100&offset=200

	const errors = {
		error: "Invalid request parameters",
		params: {},
	};

	// below code written with Copilot

	const limit = req.query.limit ? Number(req.query.limit as string) : 100;
	const offset = req.query.offset ? Number(req.query.offset as string) : 0;

	// above code written with Copilot

	if (validateQuery(limit, offset, errors)) {
		res.status(StatusCodes.BAD_REQUEST).send(errors);
		return;
	}
	// Apply pagination to your results array
	const paginatedResults = course.sections.slice(offset, offset + limit);
	// code above based on - https://canvas.ubc.ca/courses/176257/assignments/2334739

	const body = {
		total: course.sections.length,
		limit: limit,
		offset: offset,
		items: formatItemResponse(req, paginatedResults),
	};
	res.status(StatusCodes.OK).send(body);
}

export async function listSection(req: Request, res: Response, repo: CourseSectionRepository): Promise<void> {
	const course = await repo.getCourseByIdAsync(req.params.courseId);
	if (course === undefined) {
		sendNotFound(res, req.params.courseId, "course");
		return;
	}

	const section = await repo.getSectionByIdAsync(course, req.params.sectionId);
	if (section === undefined) {
		sendNotFound(res, req.params.sectionId, "section");
		return;
	}
	res.status(StatusCodes.OK).send({
		id: section.id,
		instructor: section.instructor,
		year: section.year,
		avg: section.avg,
		pass: section.pass,
		fail: section.fail,
		audit: section.audit,
		links: {
			self: `${req.originalUrl}`,
			course: `${req.originalUrl}`.split("/sections")[0],
		},
	});
}

// code below written with copilot
function validateSectionBody(req: Request, fields: any): any {
	const body = req.body;

	// instructor: required string
	if (body.instructor === undefined) {
		fields.instructor = "required but missing";
	} else if (typeof body.instructor !== "string") {
		fields.instructor = "expected a string";
	}

	// year: required integer 1900–2099
	const min = 1900;
	const max = 2099;
	if (body.year === undefined) {
		fields.year = "required but missing";
	} else if (typeof body.year !== "number" || !Number.isInteger(body.year) || body.year < min || body.year > max) {
		fields.year = "expected a number between 1900 and 2099";
	}

	// avg: required number 0–100
	if (body.avg === undefined) {
		fields.avg = "required but missing";
	} else if (typeof body.avg !== "number" || body.avg < 0 || body.avg > 100) {
		fields.avg = "expected a number between 0 and 100";
	}
	// pass, fail, audit: required integer >= 0
	["pass", "fail", "audit"].forEach((key) => {
		if (!(key in body)) {
			fields[key] = "required but missing";
		} else if (typeof body[key] !== "number" || body[key] < 0) {
			fields[key] = "expected a number >= 0";
		}
	});

	return Object.keys(fields).length > 0 ? fields : null;
}
// code above written with copilot

// written following format generated by Gemini
function formatSectionResponse(section: Section, url: string): {} {
	return {
		id: section.id,
		instructor: section.instructor,
		year: section.year,
		avg: section.avg,
		pass: section.pass,
		fail: section.fail,
		audit: section.audit,
		links: { self: `${url}`, course: `${url}`.split("/sections")[0] },
	};
}
// above written following format generated by Gemini

// function below debugged with copilot
export async function createSection(req: Request, res: Response, repo: CourseSectionRepository): Promise<void> {
	const course = await repo.getCourseByIdAsync(req.params.courseId);
	if (course === undefined) {
		return sendNotFound(res, req.params.courseId, "course");
	}

	const errors = {
		error: "Validation failed",
		fields: {},
	};

	if (validateSectionBody(req, errors.fields)) {
		res.status(StatusCodes.UNPROCESSABLE_ENTITY).send(errors);
		return;
	}

	const section = await repo.getSectionByIdAsync(course, req.params.sectionId);
	const newSection = await repo.setSectionAsync(
		course,
		req.params.sectionId,
		req.body.instructor,
		req.body.year,
		req.body.avg,
		req.body.pass,
		req.body.fail,
		req.body.audit
	);
	if (section === undefined) {
		const body = formatSectionResponse(newSection, req.originalUrl);
		res.status(StatusCodes.CREATED).send(body);
	} else {
		res.sendStatus(StatusCodes.NO_CONTENT);
	}
}
// function above debugged with copilot

export async function deleteSection(req: Request, res: Response, repo: CourseSectionRepository): Promise<void> {
	const course = await repo.getCourseByIdAsync(req.params.courseId);
	if (course === undefined) {
		return sendNotFound(res, req.params.courseId, "course");
	}
	let section = await repo.getSectionByIdAsync(course, req.params.sectionId);
	if (section === undefined) {
		return sendNotFound(res, req.params.sectionId, "section");
	}
	section = await repo.deleteSectionAsync(course, req.params.sectionId);
	res.status(StatusCodes.OK).send({
		id: section.id,
		instructor: section.instructor,
		year: section.year,
		avg: section.avg,
		pass: section.pass,
		fail: section.fail,
		audit: section.audit,
	});
}
